Repository CarnegieLearningWeb/UpGrade, pull requests merged in 2024-03, with the labels that each got.

#1348 Added json editor code to add metrics
  frontend/package-lock.json
  frontend/package.json
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/metrics/metrics.component.html
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/metrics/metrics.component.ts
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/modals/add-metrics/add-metrics.component.html
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/modals/add-metrics/add-metrics.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/modals/add-metrics/add-metrics.component.spec.ts
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/modals/add-metrics/add-metrics.component.ts
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/modals/add-metrics/add-metrics.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/profile/profile.module.ts
  frontend/projects/upgrade/src/styles.scss
Labels: enhancement

#1366 Bugfix/1365 assignedcondition null mark issue
  backend/package-lock.json
  backend/package.json
  backend/packages/Scheduler/package-lock.json
  backend/packages/Scheduler/package.json
  backend/packages/Upgrade/package-lock.json
  backend/packages/Upgrade/package.json
  backend/packages/Upgrade/src/api/controllers/ExperimentClientController.v5.ts
  backend/packages/Upgrade/src/api/controllers/validators/MarkExperimentValidator.v5.ts
  clientlibs/java/src/main/java/org/upgradeplatform/client/Main.java
  clientlibs/js/package-lock.json
  clientlibs/js/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
  types/package-lock.json
  types/package.json
Labels: release 5.1

#1343 Storing proper group exclusion and individual exclusion documents
  backend/packages/Upgrade/src/api/repositories/GroupEnrollmentRepository.ts
  backend/packages/Upgrade/src/api/services/CheckService.ts
  backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
Labels: bugfix, release 5.1

#1324 🐛 Hotfix: Fix for Exclusions logic(Simple & Within Subject Exps) and code optimization for mark call
  backend/package-lock.json
  backend/package.json
  backend/packages/Scheduler/package-lock.json
  backend/packages/Scheduler/package.json
  backend/packages/Upgrade/package-lock.json
  backend/packages/Upgrade/package.json
  backend/packages/Upgrade/src/api/repositories/GroupEnrollmentRepository.ts
  backend/packages/Upgrade/src/api/services/CheckService.ts
  backend/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts
  backend/packages/Upgrade/src/api/services/ExperimentService.ts
  backend/packages/Upgrade/test/unit/services/ExperimentAssignmentService.test.ts
  clientlibs/java/pom.xml
  clientlibs/js/package-lock.json
  clientlibs/js/package.json
  frontend/package-lock.json
  frontend/package.json
  package-lock.json
  package.json
  types/package-lock.json
  types/package.json
  types/src/Experiment/enums.ts
Labels: priority: high, backend, bugfix, release 5.1
