Repository CarnegieLearningWeb/UpGrade, pull requests merged in 2024-02, with the labels that each got.

#1284 Update delete stratification modal
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/components/stratification-factor-list/delete-stratification/delete-stratification.component.html
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/components/stratification-factor-list/delete-stratification/delete-stratification.component.scss
Labels: small-pr, frontend

#1272 🐛 Bugfix/1101: Importing large number of experiments
  backend/packages/Upgrade/src/api/services/ExperimentService.ts
  frontend/projects/upgrade/src/app/features/dashboard/home/components/modal/import-experiment/import-experiment.component.html
  frontend/projects/upgrade/src/app/features/dashboard/home/components/modal/import-experiment/import-experiment.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/home/components/modal/import-experiment/import-experiment.component.ts
  frontend/projects/upgrade/src/app/shared/shared.module.ts
Labels: frontend, bugfix

#1289 Refine table styles
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/components/preview-user/preview-user.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/components/stratification-factor-list/stratification-factor-list.component.html
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/components/stratification-factor-list/stratification-factor-list.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/home/components/experiment-list/experiment-list.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/home/pages/view-experiment/view-experiment.component.html
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/metrics/metrics.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/profile-info/profile-info.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/segments-list/segments-list.component.scss
Labels: frontend

#1290 Refine Metrics table
  frontend/projects/upgrade/src/app/features/dashboard/profile/components/metrics/metrics.component.scss
Labels: small-pr, frontend

#1287 angular 17
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/components/stratification-factor-list/delete-stratification/delete-stratification.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/components/stratification-factor-list/import-stratifications/import-stratifications.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/home/components/metrics/metrics.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/home/components/modal/export-experiment/export-experiment.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/modal/import-segment/import-segment.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/modal/new-segment/new-segment.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/modal/segment-experiment-list/segment-experiment-list.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/segment-members/segment-members.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/segments-list/segments-list.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/pages/view-segment/view-segment.theme.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/segments-root/segments-root.theme.scss
Labels: release 5.1

#1288 resolved issue of segment details page shared link not working
  frontend/projects/upgrade/src/app/core/segments/segments.data.service.ts
  frontend/projects/upgrade/src/app/core/segments/segments.service.ts
  frontend/projects/upgrade/src/app/core/segments/store/segments.effects.ts
  frontend/projects/upgrade/src/app/core/segments/store/segments.selectors.ts
  frontend/projects/upgrade/src/app/features/dashboard/segments/pages/view-segment/view-segment.component.ts
Labels: bugfix, release 5.1

#1264 Fix/issue 1104 validations
  backend/locust/load_test_upgrade_mathia.py
  backend/packages/Upgrade/src/api/controllers/ExperimentClientController.v5.ts
  backend/packages/Upgrade/src/api/controllers/validators/MarkExperimentValidator.v4.ts
  backend/packages/Upgrade/src/api/controllers/validators/MarkExperimentValidator.v5.ts
  backend/packages/Upgrade/src/api/controllers/validators/UpdateWorkingGroupValidator.ts
  clientlibs/java/src/main/java/org/upgradeplatform/requestbeans/MarkExperimentRequestData.java
  clientlibs/js/src/ApiService/ApiService.ts
Labels: release 5.1

#1213 :bug: Free groups
  backend/packages/Upgrade/src/api/repositories/GroupExclusionRepository.ts
  backend/packages/Upgrade/src/api/services/ExperimentUserService.ts
  backend/packages/Upgrade/test/integration/ExperimentAssignment/PreviewScenario4.ts
  backend/packages/Upgrade/test/integration/ExperimentAssignment/Scenario4.ts
  backend/packages/Upgrade/test/integration/ExperimentUser/WorkingGroupChangeTest1.ts
  backend/packages/Upgrade/test/integration/ExperimentUser/WorkingGroupChangeTest2.ts
  backend/packages/Upgrade/test/integration/ExperimentUser/index.ts
  backend/packages/Upgrade/test/integration/index.test.ts
  backend/packages/Upgrade/test/integration/mockData/experiment/index.ts
Labels: release 5.1

#1296 Replace skip/take with offset/limit which is relevant for sql based query.
  backend/packages/Upgrade/src/api/repositories/AnalyticsRepository.ts
  backend/packages/Upgrade/src/api/repositories/ErrorRepository.ts
  backend/packages/Upgrade/src/api/repositories/ExperimentAuditLogRepository.ts
  backend/packages/Upgrade/src/api/repositories/MonitoredDecisionPointRepository.ts
  backend/packages/Upgrade/src/api/repositories/PreviewUserRepository.ts
  backend/packages/Upgrade/src/api/services/FeatureFlagService.ts
  backend/packages/Upgrade/src/api/services/UserService.ts
  backend/packages/Upgrade/test/unit/repositories/ErrorRepository.test.ts
  backend/packages/Upgrade/test/unit/repositories/ExperimentAuditLogRepository.test.ts
  backend/packages/Upgrade/test/unit/repositories/PreviewUserRepository.test.ts
  backend/packages/Upgrade/test/unit/services/FeatureFlagService.test.ts
  backend/packages/Upgrade/test/unit/services/UserService.test.ts
Labels: release 5.1

#1298 Bug fix of post experiment rule not getting set as assign while editing from stepper
  frontend/projects/upgrade/src/app/features/dashboard/home/components/modal/new-experiment/new-experiment.component.ts
Labels: bugfix

#1293 QA bugs of import/export segment csv resolved
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/segment-members/segment-members.component.html
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/segment-members/segment-members.component.ts
Labels: release 5.1
