Repository CarnegieLearningWeb/UpGrade, pull requests merged in 2024-01, with the labels that each got.

#1193 ✨ Enhancement/1133 backend packages update Part3
  README.md
  backend/packages/Upgrade/package-lock.json
  backend/packages/Upgrade/package.json
  backend/packages/Upgrade/src/api/middlewares/SecurityNoCacheMiddleware.ts
Labels: dependencies, backend

#1190 Enhancement/export segment scv
  backend/packages/Upgrade/src/api/controllers/SegmentController.ts
  backend/packages/Upgrade/src/api/services/SegmentService.ts
  frontend/projects/upgrade/src/app/core/segments/segments.data.service.ts
  frontend/projects/upgrade/src/app/core/segments/segments.service.spec.ts
  frontend/projects/upgrade/src/app/core/segments/segments.service.ts
  frontend/projects/upgrade/src/app/core/segments/store/segments.model.ts
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/modal/export-segment/export-segment.component.html
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/modal/export-segment/export-segment.component.scss
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/modal/export-segment/export-segment.component.spec.ts
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/modal/export-segment/export-segment.component.ts
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/segments-list/segments-list.component.ts
  frontend/projects/upgrade/src/app/features/dashboard/segments/pages/view-segment/view-segment.component.ts
  frontend/projects/upgrade/src/app/features/dashboard/segments/segments.module.ts
  frontend/projects/upgrade/src/assets/i18n/en.json
  frontend/projects/upgrade/src/environments/environment-types.ts
  frontend/projects/upgrade/src/environments/environment.bsnl.ts
  frontend/projects/upgrade/src/environments/environment.demo.prod.ts
  frontend/projects/upgrade/src/environments/environment.prod.ts
  frontend/projects/upgrade/src/environments/environment.staging.ts
  frontend/projects/upgrade/src/environments/environment.ts
Labels: feature

#1177 ⚡ Single command Dockerization without nix OS dependency to Quick Start Upgrade Locally
  Makefile
  README.md
  backend/dev.Dockerfile
  dev.singleContainerApp.Dockerfile
  docker-setup.sh
  docker.nix
  frontend/dev.Dockerfile
  singleContainerApp-docker-compose.yml
Labels: dependencies, docker

#1241 🐞 Resolved bug that affects experiment pool for enrolment complete competing experiments
  backend/packages/Upgrade/src/api/repositories/ExperimentRepository.ts
Labels: bugfix

#1254 🐛 Fix auth check error to 401 from 500 and resolved setting api validator
  backend/packages/Upgrade/src/api/controllers/validators/SettingParamsValidator.ts
  backend/packages/Upgrade/src/api/middlewares/ClientLibMiddleware.ts
Labels: code improvements, bugfix

#1263 Remove spaces from the ( group ) parenthesis
  frontend/projects/upgrade/src/app/features/dashboard/home/components/experiment-participants/experiment-participants.component.ts
  frontend/projects/upgrade/src/app/features/dashboard/segments/components/segment-members/segment-members.component.ts
Labels: small-pr, design

#1268 Remove header-cell border-bottom
  frontend/projects/upgrade/src/styles.scss
Labels: frontend

#1266 Add tab-label class for styling the tab labels
  frontend/projects/upgrade/src/app/features/dashboard/experiment-users/experiment-users-root/experiment-users-root.component.html
  frontend/projects/upgrade/src/app/features/dashboard/home/components/create-query/create-query.component.html
  frontend/projects/upgrade/src/app/features/dashboard/home/pages/view-experiment/view-experiment.component.html
  frontend/projects/upgrade/src/app/features/dashboard/logs/root/logs.component.html
  frontend/projects/upgrade/src/app/features/dashboard/profile/profile-root/profile-root.component.html
  frontend/projects/upgrade/src/styles.scss
  frontend/projects/upgrade/src/styles/utility.scss
Labels: frontend

#1271 :bug: Fixing tsconfig.build.json
  backend/packages/Upgrade/commands/tsconfig.ts
Labels: bugfix
